version: "3"

services:
  db:
    image: mariadb:latest
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=pass

  api:
    build: api
    ports:
      - "80:8080"
    depends_on:
      - db
    links:
      - "db:db"
    command: sh -c "/wait && java -jar /usr/src/mymaven/target/DropWizardHibernateExample-FINAL.jar server dev.yml"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
